https://towardsdatascience.com/creating-a-custom-openai-gym-environment-for-stock-trading-be532be3910e
    https://www.kaggle.com/hwsiew/custom-gym-environment-for-reinforcement-learning

In [83]:
import numpy as np
import torch
# import torch.nn as nn
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score
from torch.autograd import Variable
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import random
import torch.nn.utils.prune as prune

def seed_all(seed):
    if not seed:
        seed = 10
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.cuda.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
seed_all(1)

dataset = pd.read_csv('./pytorch_deep_learning-master/iris.csv')

# transform species to numerics
dataset.loc[dataset.variety == 'Setosa', 'variety'] = 0
dataset.loc[dataset.variety == 'Versicolor', 'variety'] = 1
dataset.loc[dataset.variety == 'Virginica', 'variety'] = 2

train_X, test_X, train_y, test_y = train_test_split(dataset[dataset.columns[0:4]].values,
                                                    dataset.variety.values, test_size=0.2)

tensor_train_x = Variable(torch.Tensor(train_X).float())
tensor_train_y = Variable(torch.Tensor(list(train_y)).long())

tensor_test_x = Variable(torch.Tensor(test_X).float())
tensor_test_y = Variable(torch.Tensor(list(test_y)).long())

model = nn.Sequential(
    nn.Linear(4, 2),
    torch.nn.ReLU(),
    nn.Linear(2, 3),
    nn.Softmax(dim=1),
)

criterion = nn.CrossEntropyLoss()
# Construct the optimizer (Stochastic Gradient Descent in this case)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)



Sequential(
  (0): Linear(in_features=4, out_features=2, bias=True)
  (1): ReLU()
  (2): Linear(in_features=2, out_features=3, bias=True)
  (3): Softmax(dim=1)
)

In [85]:
for epoch in range(1000):
    # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(tensor_train_x)
    
    # Compute and print loss
    loss = criterion(y_pred, tensor_train_y)
#     if epoch % 10 == 0:
#         print('number of epoch', epoch, 'loss', loss.item())
#     print("here")
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()




In [ ]:
test_pred=model(tensor_test_x)
# print(test_pred)
_, predict_y = torch.max(test_pred, 1)

# print(tensor_test_y)
# print(predict_y)

print('Accuracy', accuracy_score(tensor_test_y, predict_y))

In [2]:
torch.save(model, './iris_model.pt')

In [3]:
# Model class must be defined somewhere
model = torch.load('./iris_model.pt')
model.eval()

Sequential(
  (0): Linear(in_features=4, out_features=2, bias=True)
  (1): ReLU()
  (2): Linear(in_features=2, out_features=3, bias=True)
  (3): Softmax(dim=1)
)

In [9]:
model.parameters

<bound method Module.parameters of Sequential(
  (0): Linear(in_features=4, out_features=2, bias=True)
  (1): ReLU()
  (2): Linear(in_features=2, out_features=3, bias=True)
  (3): Softmax(dim=1)
)>

In [13]:
import torch
from torch import nn
import torch.nn.utils.prune as prune
import torch.nn.functional as F

In [16]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [18]:
model=model.to(device=device)

In [56]:
h=model.named_modules('Linear')

In [2]:
import numpy as np
import torch
# import torch.nn as nn
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score
from torch.autograd import Variable
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import random


Sequential(
  (0): Linear(in_features=4, out_features=2, bias=True)
  (1): ReLU()
  (2): Linear(in_features=2, out_features=3, bias=True)
  (3): Softmax(dim=1)
)

In [30]:
import torch.nn.utils.prune as prune

In [31]:
model = torch.load('./iris_model.pt')
model.eval()

Sequential(
  (0): Linear(in_features=4, out_features=2, bias=True)
  (1): ReLU()
  (2): Linear(in_features=2, out_features=3, bias=True)
  (3): Softmax(dim=1)
)

In [32]:
model.state_dict()

OrderedDict([('0.weight',
              tensor([[ 0.5603,  0.7337, -1.0205, -0.7228],
                      [-0.4707,  0.2999, -0.1029,  0.2544]])),
             ('0.bias', tensor([ 1.2029, -0.0612])),
             ('2.weight',
              tensor([[ 1.0233,  0.0349],
                      [ 0.2230, -0.2756],
                      [-0.9948, -0.0637]])),
             ('2.bias', tensor([-1.0414,  0.3191,  1.8118]))])

In [33]:
model[0]=prune.random_unstructured(model[0], name="weight", amount=0.3)

In [34]:
model.state_dict()

OrderedDict([('0.bias', tensor([ 1.2029, -0.0612])),
             ('0.weight_orig',
              tensor([[ 0.5603,  0.7337, -1.0205, -0.7228],
                      [-0.4707,  0.2999, -0.1029,  0.2544]])),
             ('0.weight_mask',
              tensor([[1., 0., 1., 1.],
                      [1., 0., 1., 1.]])),
             ('2.weight',
              tensor([[ 1.0233,  0.0349],
                      [ 0.2230, -0.2756],
                      [-0.9948, -0.0637]])),
             ('2.bias', tensor([-1.0414,  0.3191,  1.8118]))])

In [69]:
modul=model[0]

In [70]:
prune.random_unstructured(modul, name="weight", amount=0.3)

Linear(in_features=4, out_features=2, bias=True)

In [82]:
model[0].state_dict()

OrderedDict([('bias', tensor([ 1.2029, -0.0612])),
             ('weight_orig',
              tensor([[ 0.5603,  0.7337, -1.0205, -0.7228],
                      [-0.4707,  0.2999, -0.1029,  0.2544]])),
             ('weight_mask',
              tensor([[0., 1., 1., 1.],
                      [1., 1., 1., 0.]]))])